apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stockster

resources:
  - 00-namespace.yaml
  # - postgres-statefulset.yaml
  - 01-pvc.yaml
  # - dashboard-deployment.yaml
  # - api-deployment.yaml
  - 50-scraper-configmap
  - 51-scraper-cronjob.yaml
  - 52-scraper-evening-cronjob.yaml
  # - scraper-and-loader-cronjob.yaml
  # - csv-loader-configmap.yaml
  # Legacy separate cronjobs (can be removed if not needed)
  # - cronjob-evening.yaml
  # - csv-loader-job.yaml

images:
  - name: stockster/dashboard
    newName: ghcr.io/onelock/stockster-dashboard
    newTag: latest
  - name: stockster/api
    newName: ghcr.io/onelock/stockster-api
    newTag: latest
