apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgresql-db
data:
  POSTGRES_DB: stockster_db
  POSTGRES_HOST: postgres-svc # The name of your K8s Service for 
  POSTGRES_PORT: "5432"

  postgresql.conf: |
    # PostgreSQL configuration file

    # Connection Settings
    max_connections = 20

    # Memory Settings
    shared_buffers = 512MB
    effective_cache_size = 1GB
    maintenance_work_mem = 256MB
    work_mem = 4MB

    # WAL Settings
    wal_buffers = 16MB
    min_wal_size = 512MB
    max_wal_size = 1GB

  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File

    # TYPE  DATABASE        USER            ADDRESS                 METHOD

    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    replication     all             0.0.0.0/0               md5