apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: stockster
  labels:
    app: postgresql-db
data:
  POSTGRES_DB: stockster-db
  POSTGRES_USER: stockster
  POSTGRES_HOST: postgres-stockster-service # The name of your K8s Service for 
  PGDATA: /var/lib/postgresql/data/pgdata
        