apiVersion: batch/v1
kind: Job
metadata:
  name: csv-preprocess-job
  namespace: stockster
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: csv-preprocess
          image: python:3.11
          command: ["sh", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install -y python3-venv && \
              python -m venv /venv && \
              . /venv/bin/activate && \
              pip install pandas && \
              python /app/preprocess.py
          volumeMounts:
            - name: preprocess-script
              mountPath: /app
            - name: stockster-data
              mountPath: /data
      volumes:
        - name: preprocess-script
          configMap:
            name: csv-preprocess-script
        - name: stockster-data
          persistentVolumeClaim:
            claimName: stockster-data-pvc
