apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stockster

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - pvc.yaml
  - dashboard-deployment.yaml
  - api-deployment.yaml
  - cronjob.yaml

images:
  - name: stockster/scraper
    newName: ghcr.io/onelock/stockster-scraper
    newTag: latest
  - name: stockster/dashboard
    newName: ghcr.io/onelock/stockster-dashboard
    newTag: latest
  - name: stockster/api
    newName: ghcr.io/onelock/stockster-api
    newTag: latest
