apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockster-data-pvc
  namespace: stockster
spec:
  accessModes:
    - ReadWriteOnce  # local-path only supports RWO
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # K3s default storage class
