# STRICTLY match the tag to your python library version
FROM mcr.microsoft.com/playwright/python:v1.57.0-jammy

# working directory
WORKDIR /app

# Install dependencies
COPY di_scraper/requirements_scraper.txt .
RUN pip install --no-cache-dir -r requirements_scraper.txt

# Create data directory with write permissions for any user
RUN mkdir -p /data && chmod 777 /data
RUN echo "Playwright browsers installed."

# Set environment variables
ENV CSV_OUTPUT_DIR=/data
ENV API_ENABLED=true
ENV API_URL=http://api-svc/api/v1

# Ensures that the python output i.e. the stdout and stderr streams are sent straight to terminal (e.g. your container log) without being first buffered 
ENV PYTHONUNBUFFERED=1  

# Note: We do NOT copy scrape_di.py here. 
# We will inject it via Kubernetes ConfigMap so you can update logic without rebuilding.