FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY app/requirements_api.txt .
COPY migrations/requirements_mrg.txt .
RUN pip install --no-cache-dir -r requirements_api.txt
RUN pip install --no-cache-dir -r requirements_mrg.txt


# Copy application code
COPY app/ ./app/

# Copy Alembic migrations
COPY migrations/ ./migrations/
COPY run_migrations.py .
COPY alembic.ini .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV ENVIRONMENT=production

# Expose port
EXPOSE 8000


# Run API with uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
