# STRICTLY match the tag to your python library version
FROM mcr.microsoft.com/playwright/python:v1.57.0-jammy

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir playwright==1.57.0

# Create data directory with write permissions for any user
RUN mkdir -p /data && chmod 777 /data

# Set environment variables
ENV CSV_OUTPUT_DIR=/data

# Ensures that the python output i.e. the stdout and stderr streams are sent straight to terminal (e.g. your container log) without being first buffered 
ENV PYTHONUNBUFFERED=1  

# Note: We do NOT copy scrape_di.py here. 
# We will inject it via Kubernetes ConfigMap so you can update logic without rebuilding.